# Generated by Django 5.1.1 on 2024-10-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method_temp',
        ),
    ]
