# Generated by Django 5.1.1 on 2024-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_body_alter_accessories_name_alter_carmat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='year_of_manufacture',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmat',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carmat',
            name='year_of_manufacture',
            field=models.CharField(max_length=20),
        ),
    ]
