# Generated by Django 5.1.1 on 2024-09-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_carmat_body_alter_modelname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmat',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.body', unique=True),
        ),
    ]
