# Generated by Django 5.1.1 on 2024-09-20 13:29

import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_carmat_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carmat',
            name='body',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name=viewer.models.Body),
        ),
    ]
