# Generated by Django 5.1.1 on 2024-09-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_body_name_alter_carmat_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmat',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.body'),
        ),
    ]
