# Generated by Django 5.1.1 on 2024-09-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_carmat_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmat',
            name='color_of_mat',
        ),
        migrations.RemoveField(
            model_name='carmat',
            name='color_of_trim',
        ),
    ]
