# Generated by Django 5.1.1 on 2024-09-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_carmat_color_of_mat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelname',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='carmat',
            name='body',
        ),
        migrations.RemoveField(
            model_name='carmat',
            name='model_name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year_of_manufacture', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(verbose_name='Cena')),
                ('availability', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.body')),
            ],
        ),
        migrations.AlterField(
            model_name='categorymain',
            name='name_car_mat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.product'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='viewer.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='viewer.subcategory'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.subcategory'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='CarMat',
        ),
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
