# Generated by Django 5.1.1 on 2024-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=30),
        ),
    ]
